name = "een-login"
main = "./src/index.js" # Or your main worker file

compatibility_date = "2025-04-01" # Or a more recent date

[vars]
# Other environment variables

[[kv_namespaces]]
binding = "EEN_LOGIN" 
id = "bd89d6652c3941adbe1b5a0197796bb0" 
