#!/usr/bin/env sh

# Unset potentially problematic environment variables
unset NODE_OPTIONS

# Run the pre-commit script and make sure it doesn't fail
npm run version:patch

# Exit with success to allow the commit to proceed
exit 0
