name: Slack Notification on Deployment

on:
  workflow_run:
    workflows: ["Deploy to GitHub Pages"]
    types:
      - completed

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Get version from package.json
        id: package-version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Prepare commit message
        id: commit-message
        run: |
          message="${{ github.event.workflow_run.head_commit.message }}"
          # Replace newlines with spaces and escape quotes
          message="${message//$'\n'/ }"
          message="${message//\"/\\\"}"
          echo "MESSAGE=$message" >> $GITHUB_OUTPUT

      - name: Get Repository Name
        id: repo-name
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_OUTPUT

      - name: Get GH Pages Site Name
        id: site-name
        run: |
          SITE_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 1)
          echo "SITE_NAME=$SITE_NAME" >> $GITHUB_OUTPUT

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "✅ New ${{ steps.repo-name.outputs.REPO_NAME }} Deployment to GitHub Pages (v${{ steps.package-version.outputs.VERSION }})",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Repository:* <https://github.com/${{ github.repository }}|${{ github.repository }}>\n*Branch:* <https://github.com/${{ github.repository }}/tree/${{ github.event.workflow_run.head_branch }}|${{ github.event.workflow_run.head_branch }}>"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Version:* v${{ steps.package-version.outputs.VERSION }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Commit Message:* ${{ steps.commit-message.outputs.MESSAGE }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Deployment URL:* <https://${{ steps.site-name.outputs.SITE_NAME }}.github.io/${{ steps.repo-name.outputs.REPO_NAME }}/|Vhttps://${{ steps.site-name.outputs.SITE_NAME }}.github.io>"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Workflow Run:* <${{ github.event.workflow_run.html_url }}|View Details>"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Deployed at: ${{ github.event.workflow_run.updated_at }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK 